services:
    sonata.admin.post:
        class: Imh\BaseBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu", label: "Post" }
        arguments:
            - ~
            - Acme\DemoBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [ImhBaseBundle]]